crude first edition
paperlands/paperlands.github.io pull request #2
Opened 2024-08-13 10:22 UTC by PrincetonPoh

What do you think of this crude template and the approach?

Once the template is g, i'll do up some examples for further refining

2024-08-14 03:39 UTC, ks0m1c reviewed
i dont think the RFT should be too many steps at most 3-5

2024-08-14 03:39 UTC, ks0m1c commented on _notes/rft.md
> +- Some of my students have a hard time coming up with compelling copywriting for their product launch
I think its better to start with 
Students currently [present context], but [the gap in context]. Ideally they should be able to [the ideal if the gap is crossed]

e.g Students currently have 3d printers in the homeroom but they lack the practice around CAD tooling. Ideally they are able to print simple everyday items after.

2024-08-14 03:39 UTC, ks0m1c commented on _notes/rft.md
> +e.g
```
Current Context: Students currently understand fundamental of graphics and have knowledge of lighting scenes and 3d modelling.

Identified Gap: However, they lack practical insight into procedural node based programming as being applied in real-world world of animation and 3D visualisation

Ideal Outcome: Ideally, students should be able to construct a simple 3d scene with programmable elements, that sets them up in good stead for their [3d digital game art project](link to past works)
```

2024-08-14 03:39 UTC, ks0m1c commented on _notes/rft.md
> +e.g
## **Current Context**: Students currently understand fundamental of graphics and have knowledge of lighting scenes and 3d modelling.

## **Identified Gap**: However, they lack practical insight into procedural node based programming as being applied in real-world world of animation and 3D visualisation

## **Ideal Outcome**: Ideally, students should be able to construct a simple 3d scene with programmable elements, that sets them up in good stead for their [3d digital game art project](link to past works)

2024-08-14 05:16 UTC, PrincetonPoh commented on _notes/rft.md
> +Optional details:
I think we can squeeze everything else into this part that is optional.

2024-08-15 04:16 UTC, PrincetonPoh commented
This should be quite distilled already. Lmk if got any other improvement thoughts @ks0m1c

2024-08-15 06:12 UTC, ks0m1c requested changes
looking good especially the sst ones

2024-08-15 06:12 UTC, ks0m1c commented on _notes/rft.md
> +3. Beyond just mentoring, if you're asked to TEACH a class of students about anything you wish, what would it be?
What is something you had always wanted to teach

 has something to it

or something you had always wanted others to learn about

2024-08-15 06:12 UTC, ks0m1c commented on _notes/rft.md
> +- What is your exact lesson plan?
build your lesson plan

instead of interrogating we are helping them scaffold

2024-08-15 06:12 UTC, ks0m1c commented on _notes/rft.md
> +- What is your exact lesson plan?
nested lets design an activity or two

2024-08-15 06:12 UTC, ks0m1c commented on _notes/rft.md
> +- What are some measurable metrics you would like to track?
i feel for measure it has to tie in with feedback 

how do you wish for students to respond with various time bounds
in a week 
in a month 
by the end of the term etc

2024-08-19 07:23 UTC, merged